/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farm_house_project;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;


public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
    }
    
        public void close(){
            WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
            Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Online_Shopping = new javax.swing.JButton();
        Instant_market = new javax.swing.JButton();
        Shoeitemprice = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLocation(new java.awt.Point(400, 150));

        jPanel1.setLayout(null);

        Online_Shopping.setBackground(new java.awt.Color(0, 255, 255));
        Online_Shopping.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Online_Shopping.setText("Online Shopping");
        Online_Shopping.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Online_Shopping.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Online_Shopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Online_ShoppingActionPerformed(evt);
            }
        });
        jPanel1.add(Online_Shopping);
        Online_Shopping.setBounds(50, 60, 190, 30);

        Instant_market.setBackground(new java.awt.Color(0, 255, 255));
        Instant_market.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Instant_market.setText("Instant Market");
        Instant_market.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Instant_market.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Instant_market.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Instant_marketActionPerformed(evt);
            }
        });
        jPanel1.add(Instant_market);
        Instant_market.setBounds(230, 140, 170, 30);

        Shoeitemprice.setBackground(new java.awt.Color(0, 255, 255));
        Shoeitemprice.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Shoeitemprice.setText("Show Item Price");
        Shoeitemprice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Shoeitemprice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Shoeitemprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShoeitempriceActionPerformed(evt);
            }
        });
        jPanel1.add(Shoeitemprice);
        Shoeitemprice.setBounds(370, 220, 180, 30);

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(100, 240, 110, 36);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farm_house_project/c1.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShoeitempriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShoeitempriceActionPerformed
        // TODO add your handling code here:
        new Item_Price().setVisible(true);
        close();
    }//GEN-LAST:event_ShoeitempriceActionPerformed

    private void Online_ShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Online_ShoppingActionPerformed
        // TODO add your handling code here:
        new Online_Shooping().setVisible(true);
        close();
    }//GEN-LAST:event_Online_ShoppingActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Successfully to logged out", "Welcome", HEIGHT);
        new Main_Menu().setVisible(true);
        close();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Instant_marketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Instant_marketActionPerformed
        // TODO add your handling code here:
        new Instant_Market().setVisible(true);
        close();
    }//GEN-LAST:event_Instant_marketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Instant_market;
    private javax.swing.JButton Online_Shopping;
    private javax.swing.JButton Shoeitemprice;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
