/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farm_house_project;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;




public class Instant_Market extends javax.swing.JFrame {

    /**
     * Creates new form Home_Delivary
     */
    public Instant_Market() {
        initComponents();
    }
    
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        hegg = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        degg = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        qegg = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmilk = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        gmilk = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField21 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        gu = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ba = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ma = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        gr = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        pai = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        ja = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        sa = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        ca = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        sh = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        ch = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        br = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        po = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        be = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cau = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        cab = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        lo = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cap = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        showveg = new javax.swing.JTextField();
        showegg = new javax.swing.JTextField();
        showmilk = new javax.swing.JTextField();
        showfruit = new javax.swing.JTextField();
        showfish = new javax.swing.JTextField();
        showtotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        vegetable = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        egg = new javax.swing.JCheckBox();
        milk = new javax.swing.JCheckBox();
        fruit = new javax.swing.JCheckBox();
        fish = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jTextField1.setText("      Shopping Center");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField20.setEditable(false);
        jTextField20.setText("Eggs and Milk");

        jLabel10.setText("Hen's Egg");

        hegg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hegg.setText("0");
        hegg.setToolTipText("How many pieces you need?");

        jLabel11.setText("Duck Egg");

        degg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        degg.setText("0");
        degg.setToolTipText("How many pieces you need?");

        jLabel12.setText("Quail Egg");

        qegg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qegg.setText("0");
        qegg.setToolTipText("How many pieces you need?");

        jLabel13.setText("Cow Milk");

        cmilk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cmilk.setText("0");
        cmilk.setToolTipText("How many litre you need?");

        jLabel14.setText("Goat Milk");

        gmilk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gmilk.setText("0");
        gmilk.setToolTipText("How many litre you need?");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField21.setEditable(false);
        jTextField21.setText("Fruits");
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });

        jLabel8.setText("Papaya");

        pa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pa.setText("0");
        pa.setToolTipText("How many pieces you need?");

        jLabel9.setText("Guava");

        gu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gu.setText("0");
        gu.setToolTipText("How many pieces you need?");

        jLabel16.setText("Banana");

        ba.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ba.setText("0");
        ba.setToolTipText("How many pieces you need?");

        jLabel17.setText("Mango");

        ma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ma.setText("0");
        ma.setToolTipText("How many pieces you need?");

        jLabel20.setText("Grape");

        gr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gr.setText("0");
        gr.setToolTipText("How many pieces you need?");

        jLabel29.setText("Pain Apple");

        pai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pai.setText("0");
        pai.setToolTipText("How many pieces you need?");

        jLabel30.setText("Jack fruit");

        ja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ja.setText("0");
        ja.setToolTipText("How many pieces you need?");

        jTextField33.setEditable(false);
        jTextField33.setText("Fish");
        jTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField33ActionPerformed(evt);
            }
        });

        jLabel31.setText("Salmon");

        sa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sa.setText("0");
        sa.setToolTipText("How many kilo you need?");

        jLabel32.setText("Catfish");

        ca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ca.setText("0");
        ca.setToolTipText("How many kilo you need?");

        jLabel33.setText("Shrimp");

        sh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sh.setText("0");
        sh.setToolTipText("How many kilo you need?");

        jLabel34.setText("Chitol");

        ch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ch.setText("0");
        ch.setToolTipText("How many kilo you need?");

        jTextField24.setEditable(false);
        jTextField24.setText("Vegetables");

        jLabel21.setText("Tomato");

        to.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        to.setText("0");
        to.setToolTipText("How many kilo you need?");

        jLabel22.setText("Bringel");

        br.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        br.setText("0");
        br.setToolTipText("How many kilo you need?");

        jLabel23.setText("Potato");

        po.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        po.setText("0");
        po.setToolTipText("How many kilo you need?");

        jLabel24.setText("Bean");

        be.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        be.setText("0");
        be.setToolTipText("How many kilo you need?");

        jLabel25.setText("Cauli Flower");

        cau.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cau.setText("0");
        cau.setToolTipText("How many pieces you need?");

        jLabel26.setText("Cabbage");

        cab.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cab.setText("0");
        cab.setToolTipText("How many kilo you need?");

        jLabel27.setText("Long Bean");

        lo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lo.setText("0");
        lo.setToolTipText("How many kilo you need?");

        jLabel28.setText("Capsicum");

        cap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cap.setText("0");
        cap.setToolTipText("How many kilo you need?");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Amount of Item", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 3, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setText("Cost of Vegetable");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 240, 110, 16);

        jLabel2.setText("Cost of Egg");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 110, 90, 16);

        jLabel3.setText("Cost of Milk");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 140, 70, 16);

        jLabel4.setText("Cost of Fruit");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 180, 80, 16);

        jLabel5.setText("Cost of Fish");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 210, 80, 16);

        showveg.setEditable(false);
        showveg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(showveg);
        showveg.setBounds(180, 230, 100, 28);

        showegg.setEditable(false);
        showegg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(showegg);
        showegg.setBounds(180, 100, 100, 28);

        showmilk.setEditable(false);
        showmilk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(showmilk);
        showmilk.setBounds(180, 130, 100, 28);

        showfruit.setEditable(false);
        showfruit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(showfruit);
        showfruit.setBounds(180, 170, 100, 28);

        showfish.setEditable(false);
        showfish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(showfish);
        showfish.setBounds(180, 200, 100, 28);

        showtotal.setEditable(false);
        showtotal.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        showtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        showtotal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)), "Total Amount", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 1, 14))); // NOI18N
        showtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showtotalActionPerformed(evt);
            }
        });
        jPanel1.add(showtotal);
        showtotal.setBounds(50, 420, 290, 220);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Order Entry", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 3, 18))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(null);

        vegetable.setText("Vegetable");
        vegetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegetableActionPerformed(evt);
            }
        });
        jPanel2.add(vegetable);
        vegetable.setBounds(40, 180, 87, 18);

        jLabel18.setText("Show cost of item");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(40, 30, 110, 16);

        egg.setText("Egg");
        egg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eggActionPerformed(evt);
            }
        });
        jPanel2.add(egg);
        egg.setBounds(40, 60, 87, 18);

        milk.setText("Milk");
        milk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milkActionPerformed(evt);
            }
        });
        jPanel2.add(milk);
        milk.setBounds(40, 90, 87, 18);

        fruit.setText("Fruit");
        fruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fruitActionPerformed(evt);
            }
        });
        jPanel2.add(fruit);
        fruit.setBounds(40, 120, 87, 18);

        fish.setText("Fish");
        fish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishActionPerformed(evt);
            }
        });
        jPanel2.add(fish);
        fish.setBounds(40, 150, 87, 18);

        jButton2.setText("Total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(260, 120, 55, 28);

        jButton3.setText("Receipt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(410, 120, 70, 28);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(261, 261, 261)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(26, 26, 26)
                                            .addComponent(gmilk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(26, 26, 26)
                                            .addComponent(cmilk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addGap(26, 26, 26)
                                            .addComponent(qegg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(26, 26, 26)
                                            .addComponent(degg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(26, 26, 26)
                                            .addComponent(hegg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(57, 57, 57)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel17)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(ma, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel16)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(ba, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(gu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(pa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel20)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(gr, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel29)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(pai, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel30)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(ja, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(65, 65, 65)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel34)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(ch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel33)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(sh, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel32)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel31)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(sa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(47, 47, 47)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel26)
                                            .addGap(26, 26, 26)
                                            .addComponent(cab, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel25)
                                            .addGap(26, 26, 26)
                                            .addComponent(cau, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel24)
                                            .addGap(26, 26, 26)
                                            .addComponent(be, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel23)
                                            .addGap(26, 26, 26)
                                            .addComponent(po, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel22)
                                            .addGap(26, 26, 26)
                                            .addComponent(br, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel21)
                                            .addGap(26, 26, 26)
                                            .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cap, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addGap(26, 26, 26)
                                    .addComponent(lo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(br, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(po, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(be, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(cau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(cab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27)
                                    .addComponent(lo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(hegg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(degg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(qegg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(cmilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(gmilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel8)
                                                    .addComponent(pa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel9)
                                                    .addComponent(gu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel16)
                                                    .addComponent(ba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel17)
                                                    .addComponent(ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel31)
                                                    .addComponent(sa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel32)
                                                    .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel33)
                                                    .addComponent(sh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel34)
                                                    .addComponent(ch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel20)
                                            .addComponent(gr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel29)
                                            .addComponent(pai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30)
                                    .addComponent(ja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Customer().setVisible(true);
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField33ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    int allveg = 0;
    private void vegetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegetableActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(to.getText());
        int b = Integer.parseInt(br.getText());
        int c = Integer.parseInt(po.getText());
        int d = Integer.parseInt(be.getText());
        int e = Integer.parseInt(cau.getText());
        int f = Integer.parseInt(cab.getText());
        int g = Integer.parseInt(lo.getText());
        int h = Integer.parseInt(cap.getText());
        
        int i = ((a*35)+(b*60)+(c*20)+(d*25)+(e*30)+(f*40)+(g*25)+(h*30));
        allveg = allveg + i;
        showveg.setText(""+i+" tk");
    }//GEN-LAST:event_vegetableActionPerformed
int allegg = 0;
    private void eggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eggActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(hegg.getText());
        int b = Integer.parseInt(degg.getText());
        int c = Integer.parseInt(qegg.getText());
        
        int d = ((a*10)+(b*5)+(c*8));
        showegg.setText(""+d+" tk");
        
        allegg = d + allegg;
    }//GEN-LAST:event_eggActionPerformed

    int allmilk = 0;
    private void milkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milkActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(cmilk.getText());
        int b = Integer.parseInt(gmilk.getText());
        
        int c = ((a*50)+(b*40));
        showmilk.setText(""+c+" tk");
        allmilk = allmilk + c;
    }//GEN-LAST:event_milkActionPerformed

    int allfruit = 0;
    private void fruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fruitActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(pa.getText());
        int b = Integer.parseInt(gu.getText());
        int c = Integer.parseInt(ba.getText());
        int d = Integer.parseInt(ma.getText());
        int e = Integer.parseInt(gr.getText());
        int f = Integer.parseInt(pai.getText());
        int g = Integer.parseInt(ja.getText());
        
        int h = ((a*12)+(b*8)+(c*4)+(d*10)+(e*8)+(f*20)+(g*150));
        allfruit = allfruit + h;
        showfruit.setText(""+h+" tk");
        
    }//GEN-LAST:event_fruitActionPerformed

    int allfish = 0;
    private void fishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(sa.getText());
        int b = Integer.parseInt(ca.getText());
        int c = Integer.parseInt(sh.getText());
        int d = Integer.parseInt(ch.getText());
        
        int e = ((a*180)+(b*210)+(c*150)+(d*200));
        allfish = allfish + e;
        showfish.setText(""+e+" tk");
    }//GEN-LAST:event_fishActionPerformed

    
    private void showtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showtotalActionPerformed

    int rec;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a = allegg+allmilk+allfruit+allveg+allfish;
        rec = a;
        showtotal.setText(""+rec+" tk");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Farm House Market Place\n\nEgg = "
                +allegg+" tk\nMilk = "+allmilk+" tk\nFruit = "+allfruit+
                " tk\nVegetable = "+allveg+" tk\nFish = "+allfish+
                " tk\n----------------------\nTotal =   "+rec, "Recipt",
                JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null, "Thanks for using our shooping center", 
                "Hurreee...!!!", JOptionPane.INFORMATION_MESSAGE);
        new Customer().setVisible(true);
        close();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instant_Market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instant_Market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instant_Market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instant_Market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instant_Market().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ba;
    private javax.swing.JTextField be;
    private javax.swing.JTextField br;
    private javax.swing.JTextField ca;
    private javax.swing.JTextField cab;
    private javax.swing.JTextField cap;
    private javax.swing.JTextField cau;
    private javax.swing.JTextField ch;
    private javax.swing.JTextField cmilk;
    private javax.swing.JTextField degg;
    private javax.swing.JCheckBox egg;
    private javax.swing.JCheckBox fish;
    private javax.swing.JCheckBox fruit;
    private javax.swing.JTextField gmilk;
    private javax.swing.JTextField gr;
    private javax.swing.JTextField gu;
    private javax.swing.JTextField hegg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField ja;
    private javax.swing.JTextField lo;
    private javax.swing.JTextField ma;
    private javax.swing.JCheckBox milk;
    private javax.swing.JTextField pa;
    private javax.swing.JTextField pai;
    private javax.swing.JTextField po;
    private javax.swing.JTextField qegg;
    private javax.swing.JTextField sa;
    private javax.swing.JTextField sh;
    private javax.swing.JTextField showegg;
    private javax.swing.JTextField showfish;
    private javax.swing.JTextField showfruit;
    private javax.swing.JTextField showmilk;
    private javax.swing.JTextField showtotal;
    private javax.swing.JTextField showveg;
    private javax.swing.JTextField to;
    private javax.swing.JCheckBox vegetable;
    // End of variables declaration//GEN-END:variables
}
