/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farm_house_project;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;


public class Salesman extends javax.swing.JFrame {

    /**
     * Creates new form Salesman
     */
    public Salesman() {
        initComponents();
    }
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Stock_Item = new javax.swing.JButton();
        setitemprice = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Log_out = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLocation(new java.awt.Point(400, 150));

        jPanel1.setLayout(null);

        Stock_Item.setBackground(new java.awt.Color(0, 255, 255));
        Stock_Item.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Stock_Item.setForeground(new java.awt.Color(0, 0, 153));
        Stock_Item.setText("Stock Item");
        Stock_Item.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stock_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stock_ItemActionPerformed(evt);
            }
        });
        jPanel1.add(Stock_Item);
        Stock_Item.setBounds(70, 90, 150, 32);

        setitemprice.setBackground(new java.awt.Color(0, 255, 255));
        setitemprice.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        setitemprice.setForeground(new java.awt.Color(0, 0, 153));
        setitemprice.setText("Set Item Price");
        setitemprice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setitemprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setitempriceActionPerformed(evt);
            }
        });
        jPanel1.add(setitemprice);
        setitemprice.setBounds(220, 160, 180, 32);

        jButton3.setBackground(new java.awt.Color(0, 255, 255));
        jButton3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setText("Soldout");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(400, 220, 120, 32);

        Log_out.setBackground(new java.awt.Color(255, 0, 51));
        Log_out.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Log_out.setForeground(new java.awt.Color(255, 255, 255));
        Log_out.setText("Log Out");
        Log_out.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_outActionPerformed(evt);
            }
        });
        jPanel1.add(Log_out);
        Log_out.setBounds(90, 260, 120, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farm_house_project/c1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Stock_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stock_ItemActionPerformed
        new Stock_Item().setVisible(true);
        close();
    }//GEN-LAST:event_Stock_ItemActionPerformed

    private void setitempriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setitempriceActionPerformed
        // TODO add your handling code here:
        new Setitem_price().setVisible(true);
        close();
    }//GEN-LAST:event_setitempriceActionPerformed

    private void Log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_outActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Successfully to logged out", 
                "Welcome", JOptionPane.INFORMATION_MESSAGE);
        new Main_Menu().setVisible(true);
        close();
    }//GEN-LAST:event_Log_outActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "This app is under construction", "Information", JOptionPane.INFORMATION_MESSAGE);
        
      
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salesman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salesman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salesman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salesman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salesman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Log_out;
    private javax.swing.JButton Stock_Item;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton setitemprice;
    // End of variables declaration//GEN-END:variables
}
