/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farm_house_project;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;


public class Setitem_price extends javax.swing.JFrame {

    /**
     * Creates new form Setitem_price
     */
    public Setitem_price() {
        initComponents();
    }
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Update_price = new javax.swing.JButton();
        jTextField28 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLocation(new java.awt.Point(200, 150));

        jPanel1.setLayout(null);

        Update_price.setBackground(new java.awt.Color(0, 255, 204));
        Update_price.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Update_price.setText("Update Price");
        Update_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_priceActionPerformed(evt);
            }
        });
        jPanel1.add(Update_price);
        Update_price.setBounds(390, 390, 140, 50);

        jTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField28.setText("150 tk per piece");
        jPanel1.add(jTextField28);
        jTextField28.setBounds(360, 330, 99, 28);

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel16.setText("Banana");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(293, 200, 50, 16);

        jTextField20.setEditable(false);
        jTextField20.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setText("Eggs and Milk");
        jPanel1.add(jTextField20);
        jTextField20.setBounds(30, 40, 175, 60);

        jLabel33.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel33.setText("Shrimp");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(520, 190, 50, 16);

        jTextField40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField40.setText("40 tk per kilo");
        jPanel1.add(jTextField40);
        jTextField40.setBounds(820, 290, 81, 28);

        jLabel26.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel26.setText("Cabbage");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(741, 290, 60, 16);

        jTextField39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField39.setText("30 tk per piece");
        jPanel1.add(jTextField39);
        jTextField39.setBounds(810, 260, 92, 28);

        jLabel29.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel29.setText("Pain Apple");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(269, 300, 70, 16);

        jLabel23.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel23.setText("Potato");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(765, 190, 40, 16);

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel20.setText("Grape");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(292, 270, 40, 16);

        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("8 tk per piece");
        jPanel1.add(jTextField13);
        jTextField13.setBounds(120, 200, 88, 28);

        jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField25.setText("10 tk per piece");
        jPanel1.add(jTextField25);
        jTextField25.setBounds(370, 230, 92, 28);

        jLabel22.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel22.setText("Bringel");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(749, 150, 50, 16);

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel10.setText("Hen's Egg");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(17, 120, 70, 16);

        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setText("40 tk per litre");
        jPanel1.add(jTextField15);
        jTextField15.setBounds(120, 290, 88, 28);

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setText("Papaya");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(291, 130, 50, 16);

        jLabel28.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel28.setText("Capsicum");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(727, 360, 70, 16);

        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setText("12 tk per piece");
        jPanel1.add(jTextField19);
        jTextField19.setBounds(370, 120, 92, 28);

        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("15 tk per piece");
        jPanel1.add(jTextField11);
        jTextField11.setBounds(120, 160, 88, 28);

        jTextField41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField41.setText("25 tk per kilo");
        jPanel1.add(jTextField41);
        jTextField41.setBounds(820, 320, 81, 28);

        jLabel24.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel24.setText("Bean");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(759, 220, 40, 16);

        jLabel34.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel34.setText("Chitol");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(522, 230, 40, 16);

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel12.setText("Quail Egg");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(34, 200, 60, 16);

        jLabel21.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel21.setText("Tomato");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(762, 120, 50, 16);

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel13.setText("Cow Milk");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(29, 260, 60, 16);

        jTextField36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField36.setText("60 tk per kilo");
        jPanel1.add(jTextField36);
        jTextField36.setBounds(820, 150, 81, 28);

        jTextField42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField42.setText("30 tk per kilo");
        jPanel1.add(jTextField42);
        jTextField42.setBounds(820, 350, 81, 28);

        jLabel32.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel32.setText("Catfish");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(519, 150, 50, 16);

        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.setText("4 tk per piece");
        jPanel1.add(jTextField24);
        jTextField24.setBounds(370, 190, 85, 28);

        jLabel27.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel27.setText("Long Bean");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(730, 330, 70, 16);

        jLabel25.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel25.setText("Cauli Flower");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(709, 260, 80, 16);

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel9.setText("Guava");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(305, 160, 40, 16);

        jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField26.setText("8 tk per piece");
        jPanel1.add(jTextField26);
        jTextField26.setBounds(370, 260, 90, 28);

        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField27.setText("20 tk per piece");
        jPanel1.add(jTextField27);
        jTextField27.setBounds(370, 300, 92, 28);

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel14.setText("Goat Milk");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 300, 60, 16);

        jTextField33.setEditable(false);
        jTextField33.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField33.setText("Fish");
        jTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField33ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField33);
        jTextField33.setBounds(510, 40, 159, 60);

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel11.setText("Duck Egg");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(33, 160, 60, 16);

        jTextField32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField32.setText("200 tk per kilo");
        jPanel1.add(jTextField32);
        jTextField32.setBounds(580, 220, 88, 28);

        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("8 tk per piece");
        jPanel1.add(jTextField12);
        jTextField12.setBounds(370, 150, 90, 28);

        jTextField21.setEditable(false);
        jTextField21.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setText("Fruits");
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField21);
        jTextField21.setBounds(290, 40, 172, 60);

        jTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField35.setText("35 tk per kilo");
        jPanel1.add(jTextField35);
        jTextField35.setBounds(820, 120, 81, 28);

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel17.setText("Mango");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(287, 240, 50, 16);

        jLabel31.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel31.setText("Salmon");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(523, 120, 50, 16);

        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("10 tk per piece");
        jPanel1.add(jTextField10);
        jTextField10.setBounds(110, 120, 92, 28);

        jLabel30.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel30.setText("Jack fruit");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(268, 330, 60, 16);

        jTextField37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField37.setText("20 tk per kilo");
        jPanel1.add(jTextField37);
        jTextField37.setBounds(820, 190, 81, 28);

        jTextField34.setEditable(false);
        jTextField34.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jTextField34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField34.setText("Vegetables");
        jPanel1.add(jTextField34);
        jTextField34.setBounds(740, 40, 159, 60);

        jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField29.setText("180 tk per kilo");
        jPanel1.add(jTextField29);
        jTextField29.setBounds(580, 120, 88, 28);

        jTextField38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField38.setText("25 tk per kilo");
        jPanel1.add(jTextField38);
        jTextField38.setBounds(820, 220, 81, 28);

        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("50 tk per litre");
        jPanel1.add(jTextField14);
        jTextField14.setBounds(120, 260, 88, 28);

        jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField30.setText("210 tk per kilo");
        jPanel1.add(jTextField30);
        jTextField30.setBounds(580, 150, 88, 28);

        jTextField31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField31.setText("150 tk per kilo");
        jPanel1.add(jTextField31);
        jTextField31.setBounds(580, 190, 88, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farm_house_project/c3.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField33ActionPerformed

    private void Update_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_priceActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Item price saved", 
                "Save Item", JOptionPane.INFORMATION_MESSAGE);
        new Salesman().setVisible(true);
        close();
    }//GEN-LAST:event_Update_priceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setitem_price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setitem_price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setitem_price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setitem_price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setitem_price().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update_price;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    // End of variables declaration//GEN-END:variables
}
